---

# Remove the router before removing the subnet to remove the router interfaces

- name: Remove router router1
  os_router:
    cloud: "{{ cloud_name }}"
    state: absent
    name: router1

- name: Remove router router0
  os_router:
    cloud: "{{ cloud_name }}"
    state: absent
    name: router0

- name: Remove port net10_port1
  os_port:
    cloud: "{{ cloud_name }}"
    state: absent
    name: net10_port1

- name: Remove subnet net10_subnet1
  os_subnet:
    cloud: "{{ cloud_name }}"
    state: absent
    name: net10_subnet1

- name: Remove network net10
  os_network:
    cloud: "{{ cloud_name }}"
    state: absent
    name: net10

- name: Remove port net11_port1
  os_port:
    cloud: "{{ cloud_name }}"
    state: absent
    name: net11_port1

- name: Remove subnet net11_subnet1
  os_subnet:
    cloud: "{{ cloud_name }}"
    state: absent
    name: net11_subnet1

- name: Remove network net11
  os_network:
    cloud: "{{ cloud_name }}"
    state: absent
    name: net11

- name: Remove port net12_port1
  os_port:
    cloud: "{{ cloud_name }}"
    state: absent
    name: net12_port1

- name: Remove subnet net12_subnet1
  os_subnet:
    cloud: "{{ cloud_name }}"
    state: absent
    name: net12_subnet1

- name: Remove network net12
  os_network:
    cloud: "{{ cloud_name }}"
    state: absent
    name: net12

- name: Remove port net14_port1
  os_port:
    cloud: "{{ cloud_name }}"
    state: absent
    name: net14_port1

- name: Remove subnet net14_subnet1
  os_subnet:
    cloud: "{{ cloud_name }}"
    state: absent
    name: net14_subnet1

- name: Remove network net14
  os_network:
    cloud: "{{ cloud_name }}"
    state: absent
    name: net14