site_name: oVirt System Tests Docs
site_description: oVirt system tests documentation
site_author: oVirt system tests team
site_dir: docs-out
theme: readthedocs
repo_url: https://github.com/oVirt/ovirt-system-tests
repo_name: GitHub
pages:
  - HOME: 'README.md'
  - README: 'README.md'
  - FAQ: 'FAQ.md
